apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "amqp-sender.fullname" . }}
  labels:
{{ include "amqp-sender.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "amqp-sender.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "amqp-sender.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: SERVER_MANAGER_PORT
              value: "9090"
            - name: NODE_ENV
              value: {{ .Values.config.nodeEnv | quote }}
            - name: RABBITMQ_HOST
              value: {{ .Values.config.rabbitmq.host | quote }}
            - name: RABBITMQ_USER
              value: {{ .Values.config.rabbitmq.user | quote }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.config.rabbitmq.passwordSecret }}
                  key: rabbitmq-password
            - name: RABBITMQ_MESSAGETYPE
              value: {{ .Values.config.rabbitmq.messageType | quote }}
            - name: RABBITMQ_EXCHANGENAME
              value: {{ .Values.config.rabbitmq.exchangeName | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
          livenessProbe:
            httpGet:
              path: /info
              port: metrics
          readinessProbe:
            httpGet:
              path: /info
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
