apiVersion: v1
kind: Service
metadata:
  name: {{ include "amqp-sender.fullname" . }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
  labels:
{{ include "amqp-sender.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "amqp-sender.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
