releases:
  - name: amqp-receiver
    chart: ./helm/amqp-receiver
    namespace: app
    values:
      - aws-dev/amqp-receiver.values.yaml.gotmpl

  - name: amqp-sender
    chart: ./helm/amqp-sender
    namespace: app
    values:
      - aws-dev/amqp-sender.values.yaml.gotmpl
